[build]
  # Edge Handlers live in 'edge-handlers/'
  edge_handlers = "edge-handlers"

# Redirect all image requests on our domain to the Edge Handler
[[redirects]]
  from = "/*.(png|jpg|jpeg|gif)"
  to = "/_img/:splat?url=https://komiku.id/:splat"
  status = 200
  force = true

# Register the Edge Handler at path '/_img/*'
[[edge_handlers]]
  path = "/_img/*"
  handler = "compress"
