[build]
  command = "npm install"  # Ini akan menginstal semua dependensi yang terdaftar di package.json
  publish = "dist"         # Ganti dengan folder publik Anda jika berbeda

[functions]
  external_node_modules = ["sharp"]  # Daftar modul eksternal yang ingin Anda gunakan

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/compress?url=:splat"
  status = 200
  force = true

[context.production]
  command = "npm run build"
  publish = "dist"  # Ganti dengan folder publik Anda jika berbeda

[context.staging]
  command = "npm run build"
  publish = "dist"  # Ganti dengan folder publik Anda jika berbeda

[[plugins]]
  package = "@netlify/plugin-nextjs"
